### ISSUE TITLE
functional tests do not work after update

### ISSUE THREAD

**Issue by rmcgranaghan** [lkilcommons/OvationPyme#9]
After pulling the latest version of OvationPyme after the updates to fix average energy, the functional tests do not work with traceback (for Python 3.6):

Traceback (most recent call last):
  File "ovationpyme/functionaltests.py", line 188, in <module>
    fiN = draw_interpolated_conductance(new_mlat, new_mlt, dt, startdt, enddt, 'N')
  File "ovationpyme/functionaltests.py", line 15, in draw_interpolated_conductance
    estimator = ovation_prime.ConductanceEstimator(startdt, enddt)
TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given

**Comment by ljlamarche** [comment]
I get an almost identical error for Python 2.7.15
```
Traceback (most recent call last):
  File "ovationpyme/functionaltests.py", line 188, in <module>
    fiN = draw_interpolated_conductance(new_mlat, new_mlt, dt, startdt, enddt, 'N')
  File "ovationpyme/functionaltests.py", line 15, in draw_interpolated_conductance
    estimator = ovation_prime.ConductanceEstimator(startdt, enddt)
TypeError: __init__() takes at most 2 arguments (3 given)
```

**Comment by lkilcommons** [comment]
Thank you for your bug reports, Leslie and Ryan. In the latest commit, I've fixed this problem and added some additional visual testing scripts for testing that the solar wind data which is driving OvationPyme is being loaded and processed correctly.
